---
- name: Hardware Report
  hosts: all
  gather_facts: yes
  tasks:
  ######################################
  # 1) URL/hwreport.empty --> /root/hwreport.txt
  # 2) Edit a file - /root/hwreport.txt 
  # 3) Fetch the files - ~/project/results/*
  ######################################
    - name: 1) URL/hwreport.empty --> /root/hwreport.txt
      ansible.builtin.get_url:
        url: http://192.168.10.10/hwreport.empty
        dest: /root/hwreport.txt

    - name: 2) Edit a file - /root/hwreport.txt
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: '^HOST'
        line: "HOST={{ inventory_hostname_short }}"
        state: present

    - name: 2) Edit a file - /root/hwreport.txt
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: '^BIOS'
        line: "BIOS={{ ansible_facts['bios_version'] }}"
        state: present

    - name: 2) Edit a file - /root/hwreport.txt
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: '^MEMORY'
        line: "MEMORY={{ ansible_facts['memtotal_mb'] }}"
        state: present

    - name: 2) disk size - /dev/sda
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: '^SDA_DISK_SIZE'
        line: |
          {% if ansible_facts['devices']['sda'] is defined %}
          SDA_DISK_SIZE={{ ansible_facts['devices']['sda']['size']  }}
          {% else %}
          SDA_DISK_SIZE=NONE
          {% endif %}
        state: present

    - name: 2) disk size - /dev/sdb
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: '^SDB_DISK_SIZE'
        line: |
          {% if ansible_devices.sdb is defined %}
          SDB_DISK_SIZE={{ ansible_devices.sdb.size }}
          {% else %}
          SDB_DISK_SIZE=NONE
          {% endif %}
        state: present

    - name: 2) disk size - /dev/sdc
      lineinfile:
        path: /root/hwreport.txt
        regexp: '^SDC_DISK'
        line: |
          {% if ansible_facts['devices']['sdc'] is defined %}
          SDC_DISK_SIZE={{ ansible_facts['devices']['sdc']['size'] }}
          {% else %}
          SDC_DISK_SIZE=NONE
          {% endif %}
        state: present

    - name: 3) Fetch the files - ~/project/results/
      ansible.builtin.fetch:
        src: /root/hwreport.txt
        dest: results









